### ISSUE TITLE
failed to run on osx 10.10

### ISSUE THREAD

**Issue by hanoii** [sdelements/lets-chat#227]
Just checked it out, did npm install with nodejs 0.12 and when trying to run it I got:

Failed at the lets-chat@0.3.0 prestart script 'migroose'.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     migroose
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.

```
$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart lets-chat@0.3.0
7 verbose unsafe-perm in lifecycle true
8 info lets-chat@0.3.0 Failed to exec prestart script
9 verbose stack Error: lets-chat@0.3.0 prestart: `migroose`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1008:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
10 verbose pkgid lets-chat@0.3.0
11 verbose cwd /Users/ariel/Sites/lets-chat
12 error Darwin 14.1.0
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.12.0
15 error npm  v2.5.1
16 error code ELIFECYCLE
17 error lets-chat@0.3.0 prestart: `migroose`
17 error Exit status 1
18 error Failed at the lets-chat@0.3.0 prestart script 'migroose'.
18 error This is most likely a problem with the lets-chat package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     migroose
18 error You can get their info via:
18 error     npm owner ls lets-chat
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

any ideas?

**Comment by sibartlett** [comment]
I'll test nodejs 0.12 soon - we've been using nodejs 0.10 on OS X 10.10

**Comment by hanoii** [comment]
OK, I think I had that one installed before and got the same error, then updated, but not 100% sure which version I had before.

**Comment by sibartlett** [comment]
Can you try running the following two commands?

```
npm run-script migrate
node app.js
```

**Comment by faebser** [comment]
Hi,
I'm running Linux 3.18.6-1-ARCH with node v0.10.36 and npm  v2.5.0.
I got the same error starting the app.

I tried to run
```
npm run-script migrate
```
but no luck:

```
> lets-chat@0.3.0 migrate /home/faebser/opt/lets-chat
> migroose

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

/home/faebser/opt/lets-chat/migroose.js:10
            if (err) { throw err; }
                             ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/home/faebser/opt/lets-chat/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
    at emit (events.js:106:17)
    at null.<anonymous> (/home/faebser/opt/lets-chat/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/home/faebser/opt/lets-chat/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:442:13)

npm ERR! Linux 3.18.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run-script" "migrate"
npm ERR! node v0.10.36
npm ERR! npm  v2.5.0
npm ERR! code ELIFECYCLE
npm ERR! lets-chat@0.3.0 migrate: `migroose`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the lets-chat@0.3.0 migrate script 'migroose'.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     migroose
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/faebser/opt/lets-chat/npm-debug.log
```
the output of npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run-script', 'migrate' ]
2 info using npm@2.5.0
3 info using node@v0.10.36
4 verbose run-script [ 'premigrate', 'migrate', 'postmigrate' ]
5 info premigrate lets-chat@0.3.0
6 info migrate lets-chat@0.3.0
7 verbose unsafe-perm in lifecycle true
8 info lets-chat@0.3.0 Failed to exec migrate script
9 verbose stack Error: lets-chat@0.3.0 migrate: `migroose`
9 verbose stack Exit status 8
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:98:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:98:17)
9 verbose stack     at maybeClose (child_process.js:766:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
10 verbose pkgid lets-chat@0.3.0
11 verbose cwd /home/faebser/opt/lets-chat
12 error Linux 3.18.6-1-ARCH
13 error argv "/usr/bin/node" "/usr/bin/npm" "run-script" "migrate"
14 error node v0.10.36
15 error npm  v2.5.0
16 error code ELIFECYCLE
17 error lets-chat@0.3.0 migrate: `migroose`
17 error Exit status 8
18 error Failed at the lets-chat@0.3.0 migrate script 'migroose'.
18 error This is most likely a problem with the lets-chat package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     migroose
18 error You can get their info via:
18 error     npm owner ls lets-chat
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

do you need some more info?

**Comment by danieldiekmeier** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart lets-chat@0.3.0
6 verbose unsafe-perm in lifecycle true
7 info lets-chat@0.3.0 Failed to exec prestart script
8 verbose stack Error: lets-chat@0.3.0 prestart: `migroose`
8 verbose stack Exit status 1
8 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
8 verbose stack     at EventEmitter.emit (events.js:110:17)
8 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
8 verbose stack     at ChildProcess.emit (events.js:110:17)
8 verbose stack     at maybeClose (child_process.js:1008:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
9 verbose pkgid lets-chat@0.3.0
10 verbose cwd /Users/Daniel/dev/javascript/lets-chat
11 error Darwin 14.1.0
12 error argv "node" "/usr/local/bin/npm" "start"
13 error node v0.12.0
14 error npm  v2.5.1
15 error code ELIFECYCLE
16 error lets-chat@0.3.0 prestart: `migroose`
16 error Exit status 1
17 error Failed at the lets-chat@0.3.0 prestart script 'migroose'.
17 error This is most likely a problem with the lets-chat package,
17 error not with npm itself.
17 error Tell the author that this fails on your system:
17 error     migroose
17 error You can get their info via:
17 error     npm owner ls lets-chat
17 error There is likely additional logging output above.
18 verbose exit [ 1, true ]
```

I have the same problem.

**Comment by derickbailey** [comment]
@faebser from the above stack trace:

> Error: failed to connect to [localhost:27017]

do you have a MongoDB instance running on your computer? if not, you will need that. 

@sibartlett i'll install node v0.12 and see if things work correctly. is the lack of database connection something that should be handled better in derickbailey/migroose? is this documentation that should be updated in lets-chat, so people know where to change the connection string?

**Comment by faebser** [comment]
@derickbailey I just followed the wiki and therefore I assume that I don't have a mongoDB Instance running. You just probably mention this in the wiki.

**Comment by hhaidar** [comment]
@faebser It's definitely listed on the [installation page](https://github.com/sdelements/lets-chat/wiki/Installation), we can probably make it easier to see though.

**Comment by faebser** [comment]
@hhaidar shit, now I can see it too. sry, maybe a quick notice that you have to start it together with the app?

**Comment by hanoii** [comment]
Yup, 

```
brew install mongodb
mongod --config /usr/local/etc/mongod.conf
```

did it for me, seems to work just fine on node 0.12 as well.

nice one, I'll have to do something on nodejs at some point!

**Comment by derickbailey** [comment]
@hanoii you should! it's fun :) i've got a short screencast at the bottom of this post, to show you how to write your first node code: https://sub.watchmecode.net/getting-started-with-nodejs-installing-and-writing-your-first-code/

**Comment by hanoii** [comment]
@derickbailey thanks, will definitely take a look!

**Comment by hhaidar** [comment]
@danieldiekmeier did you end up getting it to work?

**Comment by danieldiekmeier** [comment]
@hhaidar Yes, it was because of MongoDB not running. Maybe you can check for that on starting the app and give a clearer error message? Other than that, loving it so far.

**Comment by hhaidar** [comment]
@danieldiekmeier awesome, good to hear!

**Comment by ahmadsolehin** [comment]
can anyone help me? i get same error.. migroose.js problem..how to fix this?
