### ISSUE TITLE
Failed to launch letschat with fig on fresh new ubuntu environment

### ISSUE THREAD

**Issue by hayderimran7** [sdelements/lets-chat#295]
I tried to set up letschat using docker/fig on a new ubuntu 14 environment but it has been failing again and again.
Here is the output im getting after runing ` fig up` . 
```
Attaching to letschat_app_1
app_1 | 
app_1 | > lets-chat@0.3.3 prestart /usr/src/app
app_1 | > migroose
app_1 | 
app_1 | 
app_1 | /usr/src/app/migroose.js:10
app_1 | if (err) { throw err; }
app_1 | ^
app_1 | Error: failed to connect to [db:27017]
app_1 | at null.<anonymous> (/usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
app_1 | at emit (events.js:106:17)
app_1 | at null.<anonymous> (/usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
app_1 | at emit (events.js:98:17)
app_1 | at Socket.<anonymous> (/usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
app_1 | at Socket.emit (events.js:95:17)
app_1 | at net.js:834:16
app_1 | at process._tickCallback (node.js:442:13)
app_1 | 
app_1 | npm ERR! Linux 3.13.0-45-generic
app_1 | npm ERR! argv "node" "/usr/local/bin/npm" "start"
app_1 | npm ERR! node v0.10.36
app_1 | npm ERR! npm v2.5.0
app_1 | npm ERR! code ELIFECYCLE
app_1 | npm ERR! lets-chat@0.3.3 prestart: migroose
app_1 | npm ERR! Exit status 8
app_1 | npm ERR! 
app_1 | npm ERR! Failed at the lets-chat@0.3.3 prestart script 'migroose'.
app_1 | npm ERR! This is most likely a problem with the lets-chat package,
app_1 | npm ERR! not with npm itself.
app_1 | npm ERR! Tell the author that this fails on your system:
app_1 | npm ERR! migroose
app_1 | npm ERR! You can get their info via:
app_1 | npm ERR! npm owner ls lets-chat
app_1 | npm ERR! There is likely additional logging output above.
app_1 | 
app_1 | npm ERR! Please include the following file with any support request:
app_1 | npm ERR! /usr/src/app/npm-debug.log
letschat_app_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
```

**Comment by hayderimran7** [comment]
Found the issue: i was running out of hard disk (duh :/ )
Did a ` docker logs '<letschat-container-id>' ` . and it instantly showed me mongo requires more disk space for my vm.
Closing this issue, as i spin up a new vm with ~ 20Gb allocated and app is running fine now, :)
```
db_1  | 2015-02-22T05:47:18.065+0000 [initandlisten] connection accepted from 172.17.0.4:45838 #16 (10 connections now open)
db_1  | 2015-02-22T05:47:18.070+0000 [conn12] build index on: letschat.messages properties: { v: 1, key: { _id: 1 }, name: "_id_", ns: "letschat.messages" }
db_1  | 2015-02-22T05:47:18.071+0000 [conn12] 	 added index to empty collection
db_1  | 2015-02-22T05:47:18.072+0000 [conn12] build index on: letschat.messages properties: { v: 1, key: { posted: 1 }, name: "posted_1", ns: "letschat.messages", background: true, safe: null }
db_1  | 2015-02-22T05:47:18.073+0000 [conn12] 	 added index to empty collection
app_1 | 
app_1 | ██╗     ███████╗████████╗███████╗     ██████╗██╗  ██╗ █████╗ ████████╗
app_1 | ██║     ██╔════╝╚══██╔══╝██╔════╝    ██╔════╝██║  ██║██╔══██╗╚══██╔══╝
app_1 | ██║     █████╗     ██║   ███████╗    ██║     ███████║███████║   ██║   
app_1 | ██║     ██╔══╝     ██║   ╚════██║    ██║     ██╔══██║██╔══██║   ██║   
app_1 | ███████╗███████╗   ██║   ███████║    ╚██████╗██║  ██║██║  ██║   ██║   
app_1 | ╚══════╝╚══════╝   ╚═╝   ╚══════╝     ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝
app_1 | 
app_1 | Release 0.3.3
app_1 | 
db_1  | 2015-02-22T05:47:18.098+0000 [conn12] build index on: letschat.messages properties: { v: 1, key: { room: 1, posted: -1, _id: 1 }, name: "room_1_posted_-1__id_1", ns: "letschat.messages", background: true, safe: null }
```
so the gist is to have ~20gb space for an ubuntu based vm , and the app will run fine with fig :+1:

**Comment by funkaoshi** [comment]
These are my favourite sorts of deployment queries! :smiley:
