### ISSUE TITLE
Dependency icu is not listed

### ISSUE THREAD

**Issue by hobarrera** [sdelements/lets-chat#375]
The installation guide lists node.js, mongodb and python2 as the only dependencies. ICU is also required to run npm install successfully:

```
# npm install
 
> node-stringprep@0.7.0 install /home/lets-chat/lets-chat/node_modules/node-xmpp-core/node_modules/node-stringprep
> node-gyp rebuild

which: icu-config: Command not found.
gyp: Call to 'which icu-config > /dev/null || echo n' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System OpenBSD 5.7
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lets-chat/lets-chat/node_modules/node-xmpp-core/node_modules/node-stringprep
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
```

**Comment by hhaidar** [comment]
What platform is this?

**Comment by hobarrera** [comment]
OpenBSD:

    # uname -a
    OpenBSD elysion.barrera.io 5.7 GENERIC.MP#895 amd64

I already had icu installed on my other test system (ArchLinux) and uninstalling it would have broken my installation, so I can't confirm if it's necessary (or not) on other platforms.
