### ISSUE TITLE
Crash when OTR is enable in a chat room

### ISSUE THREAD

**Issue by pathetiq** [sdelements/lets-chat#383]
Hi guys,

lets chat will crash if OTR is enabled in a public room with an XMPP client.
Client used: profanity
Version use: develop branches 0.3.8

The crash seems to simply doesn't handle when user_id is null. 

Crash info:
/usr/local/lets-chat-develop/app/xmpp/msg-processors/user-message.js:36
                user: user._id,
                          ^
TypeError: Cannot read property '_id' of null
    at null.<anonymous> (/usr/local/lets-chat-develop/app/xmpp/msg-processors/user-message.js:36:27)
    at Promise.<anonymous> (/usr/local/lets-chat-develop/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/usr/local/lets-chat-develop/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/usr/local/lets-chat-develop/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Object.cb (/usr/local/lets-chat-develop/node_modules/mongoose/lib/query.js:1150:30)
    at Object._onImmediate (/usr/local/lets-chat-develop/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:354:15)

npm ERR! lets-chat@0.3.8 start: `node app.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the lets-chat@0.3.8 start script.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-54-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /usr/local/lets-chat-develop
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/lets-chat-develop/npm-debug.log
npm ERR! not ok code 0
 

Thanks

**Comment by geoffwhittington** [comment]
thanks @pathetiq ! We'll take a look

**Comment by sibartlett** [comment]
@pathetiq I tried to reproduce the issue. I added some error-handling, so you could try the latest code on develop? If it persists, could you provide the exact Profanity command you're using to start the OTR conversation?

**Comment by pathetiq** [comment]
Seems to work thanks! :)
