### ISSUE TITLE
App fails to load due to missing dependencies

### ISSUE THREAD

**Issue by pete-otaqui** [sdelements/lets-chat#414]
I just checked out the current master (f034fde) ran `npm install`, `grunt bower` (which is not a documented requirement) and then `npm start`.

When I tried to load http://localhost:5000, I received errors about missing *.less files in the browser, specifically selectize related.

I've had a look around and I can't work out where these apparent dependencies are defined (they don't seem to be required by npm or bower).

```
Template render error: Error: [LessEngine] FileError: '../js/vendor/selectize/selectize.bootstrap3.css' wasn't found. Tried - /home/pete/Projects/lets-chat/media/js/vendor/selectize/selectize.bootstrap3.css,/home/pete/Projects/lets-chat/media/js/vendor/selectize/selectize.bootstrap3.css,/home/pete/Projects/lets-chat/media/js/vendor/selectize/selectize.bootstrap3.css,/home/pete/Projects/lets-chat/media/js/vendor/selectize/selectize.bootstrap3.css,../js/vendor/selectize/selectize.bootstrap3.css in /home/pete/Projects/lets-chat/media/less/vendor.less:20:0
---
19 @import (inline) '../js/vendor/selectize/selectize.css';
20 @import (inline) '../js/vendor/selectize/selectize.bootstrap3.css';
21   (in /home/pete/Projects/lets-chat/media/less/vendor.less)
   at lessError (/home/pete/Projects/lets-chat/node_modules/connect-assets/node_modules/mincer/lib/mincer/engines/less_engine.js:76:10)
   at /home/pete/Projects/lets-chat/node_modules/connect-assets/node_modules/mincer/lib/mincer/engines/less_engine.js:157:17
   at /home/pete/Projects/lets-chat/node_modules/less/lib/less/render.js:26:35
   at /home/pete/Projects/lets-chat/node_modules/less/lib/less/parse.js:62:33
   at Object.finish [as _finish] (/home/pete/Projects/lets-chat/node_modules/less/lib/less/parser/parser.js:180:28)
   at Object.ImportVisitor._onSequencerEmpty (/home/pete/Projects/lets-chat/node_modules/less/lib/less/visitors/import-visitor.js:35:14)
   at ImportSequencer.tryRun (/home/pete/Projects/lets-chat/node_modules/less/lib/less/visitors/import-sequencer.js:50:14)
   at Object.ImportVisitor.run (/home/pete/Projects/lets-chat/node_modules/less/lib/less/visitors/import-visitor.js:29:25)
   at Object.Parser.parse (/home/pete/Projects/lets-chat/node_modules/less/lib/less/parser/parser.js:189:22)
   at Object.parse (/home/pete/Projects/lets-chat/node_modules/less/lib/less/parse.js:61:18)
```

Commenting out all the imports to files that don't exist in `media/less/vendor.less` still results in template render errors about socket.io:

```
Template render error: Error: [DirectiveProcessor] Could not find file 'vendor/socket.io/socket.io.js'.  (in /home/pete/Projects/lets-chat/media/js/vendor.js:1)
   at Context.resolve (/home/pete/Projects/lets-chat/node_modules/connect-assets/node_modules/mincer/lib/mincer/context.js:279:13)
   at Context.requireAsset (/home/pete/Projects/lets-chat/node_modules/connect-assets/node_modules/mincer/lib/mincer/context.js:333:19)
   at Object.DIRECTIVE_HANDLERS.require (/home/pete/Projects/lets-chat/node_modules/connect-assets/node_modules/mincer/lib/mincer/processors/directive_processor.js:108:18)
   at /home/pete/Projects/lets-chat/node_modules/connect-assets/node_modules/mincer/lib/mincer/processors/directive_processor.js:315:31
   at Function.forEach (/home/pete/Projects/lets-chat/node_modules/connect-assets/node_modules/mincer/node_modules/lodash/dist/lodash.js:3297:15)
   at DirectiveProcessor.processDirectives (/home/pete/Projects/lets-chat/node_modules/connect-assets/node_modules/mincer/lib/mincer/processors/directive_processor.js:308:5)
   at DirectiveProcessor.evaluate (/home/pete/Projects/lets-chat/node_modules/connect-assets/node_modules/mincer/lib/mincer/processors/directive_processor.js:288:8)
   at /home/pete/Projects/lets-chat/node_modules/connect-assets/node_modules/mincer/lib/mincer/context.js:450:26
   at Function.forEach (/home/pete/Projects/lets-chat/node_modules/connect-assets/node_modules/mincer/node_modules/lodash/dist/lodash.js:3297:15)
   at Context.evaluate (/home/pete/Projects/lets-chat/node_modules/connect-assets/node_modules/mincer/lib/mincer/context.js:445:5)
```

**Comment by sibartlett** [comment]
There's no need to run the bower task - we're going to remove it. You'll want to do a git reset, to undo the changes that the bower task did.

**Comment by pete-otaqui** [comment]
Ah whoops sorry!
