### ISSUE TITLE
Crash when Missing email field in LDAP

### ISSUE THREAD

**Issue by pathetiq** [sdelements/lets-chat#422]
Hey guys,

When the email field is not filled in the active directory the application crash because the empty email isn't catch.

This is the 0.3.9 develop version.
 

See the following error:
```
/home/node/develop/node_modules/lets-chat-ldap/lib/auth.js:93
    var email = ldapEmail.toString().split(',')[0];
                          ^
TypeError: Cannot call method 'toString' of undefined
    at Function.Ldap.createLdapUser (/home/node/develop/node_modules/lets-chat-ldap/lib/auth.js:93:27)
    at Promise.<anonymous> (/home/node/develop/node_modules/lets-chat-ldap/lib/auth.js:82:18)
    at Promise.<anonymous> (/home/node/develop/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/home/node/develop/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/home/node/develop/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Object.cb (/home/node/develop/node_modules/mongoose/lib/query.js:1150:30)
    at Object._onImmediate (/home/node/develop/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:354:15)

npm ERR! lets-chat@0.3.9 start: `node app.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the lets-chat@0.3.9 start script.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/node/develop
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/node/develop/npm-debug.log
```

Thanks

Patrick

**Comment by hhaidar** [comment]
@pathetiq email is a required field for users. Before we consider changing that, are you guys able to just supply an email?

**Comment by pathetiq** [comment]
@hhaidar Yes it is all good and fixed on our side, it is mostly for you to had an error message back to the user saying that email or other info is missing in it's account and it is required to connect, instead that it crash the app completely.

**Comment by hhaidar** [comment]
ah thanks @pathetiq <3
