### ISSUE TITLE
Migroose not working on Mac

### ISSUE THREAD

**Issue by daMogli** [sdelements/lets-chat#441]
Users/ayushgupta/lets-chat/migroose.js:10
            if (err) { throw err; }
                             ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/Users/ayushgupta/lets-chat/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
    at emit (events.js:118:17)
    at null.<anonymous> (/Users/ayushgupta/lets-chat/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at emit (events.js:110:17)
    at Socket.<anonymous> (/Users/ayushgupta/lets-chat/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "run-script" "migrate"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE
npm ERR! lets-chat@0.3.10 migrate: `migroose`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lets-chat@0.3.10 migrate script 'migroose'.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     migroose
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ayushgupta/lets-chat/npm-debug.log

**Comment by bkkilaru** [comment]
Few quick thoughts:

May want to make sure MongoDB is running.

    mongod

If there's an issue with that:

    killall -15 mongod

To deal with possible npm issue:

    rm -rf node_modules
    npm cache clean
    npm install

**Comment by hhaidar** [comment]
Yea looks like mongo is not running. See http://docs.mongodb.org/manual/installation/

**Comment by daMogli** [comment]
thanks for the quick reply. that got it working :)

**Comment by hhaidar** [comment]
@daMogli good to hear, enjoy! :D
