### ISSUE TITLE
Error when npm start (lets chat)

### ISSUE THREAD

**Issue by bondiep** [sdelements/lets-chat#470]
I have error with lets-chat, please help me to solve the problem !
mail :dokhaccanh791990@gmail.com 

> lets-chat@0.3.12 prestart /Users/mac/lets-chat
> migroose

[Error: Module did not self-register.]
js-bson: Failed to load c++ bson extension, using pure JS version
/Users/mac/lets-chat/migroose.js:13
            if (err) { throw err; }
                             ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/Users/mac/lets-chat/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
    at emit (events.js:118:17)
    at null.<anonymous> (/Users/mac/lets-chat/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at emit (events.js:110:17)
    at Socket.<anonymous> (/Users/mac/lets-chat/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! lets-chat@0.3.12 prestart: `migroose`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lets-chat@0.3.12 prestart script 'migroose'.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     migroose
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mac/lets-chat/npm-debug.log

**Comment by mpartipilo** [comment]
It looks like mongodb is not running.

**Comment by hhaidar** [comment]
@mpartipilo @bondiep yup! http://docs.mongodb.org/manual/installation/
