### ISSUE TITLE
How to restart letschat after a settings change in docker?

### ISSUE THREAD

**Issue by 0vermind** [sdelements/lets-chat#514]
I installed docker image of lets-chat 0.4.0
After changing the settings.yml how can I restart lets-chat?
Entering the docker and doing:

>node app restart or node restart

did not help. I also did a restart of the docker:

But I get this error:

>module.js:338
    throw err;
          ^
Error: Cannot find module '/usr/src/app/start'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Please help, docker image is not a viable solution if I can restart it.

**Comment by mmeinert** [comment]
If you undo your changes in settings.yml, does it work ?
Could you explain what you changed ?
Do you run docker with `docker run` or with `docker-compose up` ?

@sibartlett @hhaidar Does the docker image could include [pm2](https://github.com/Unitech/pm2) to facilitate the init ?

**Comment by sibartlett** [comment]
Currently the Docker image only support environment variables, but I'll be looking into adding a Docker volume for configuration.

**Comment by 0vermind** [comment]
Great to hear @sibartlett , will be a lot useful.
Anyway after 24 hour of running docker image it crashed. :(
Here is the logs from docker logs: 

>Killed
npm ERR! Linux 3.13.0-52-generic
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.1
npm ERR! code ELIFECYCLE
npm ERR! lets-chat@0.4.0 start: `node app.js`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the lets-chat@0.4.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.
npm ERR! Linux 3.13.0-52-generic
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.1
npm ERR! path npm-debug.log.7da2e9feb6af80ea1c45d89105a542fd
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! Error: EACCES, open 'npm-debug.log.7da2e9feb6af80ea1c45d89105a542fd'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, open 'npm-debug.log.7da2e9feb6af80ea1c45d89105a542fd']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: 'npm-debug.log.7da2e9feb6af80ea1c45d89105a542fd' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

> lets-chat@0.4.0 prestart /usr/src/app
> migroose

>Cannot load StringPrep-0.7.0 bindings (using fallback). You may need to `npm install node-stringprep`

Any help approcciante. :)

**Comment by TimWolla** [comment]
> Currently the Docker image only support environment variables, but I'll be looking into adding a Docker volume for configuration.

Actually it's way easier. I recommend creating a custom container on top of yours:

```
# cat Dockerfile 
FROM sdelements/lets-chat

COPY settings.yml /usr/src/app/settings.yml
```

And then: ```
# docker build -t timwolla/lets-chat .
# docker stop lc; docker rm lc; docker run -d -p 127.0.0.1:5001:8080 -p 5222:5222 --link mongo-lc:mongo --name lc --volumes-from=lc-data timwolla/lets-chat
```

And then your new container is up and running :smiley:

**Comment by sibartlett** [comment]
@0vermind @TimWolla I've added a config volume to the Docker image, so you can mount a directory containing settings.yml
