### ISSUE TITLE
Unable to use basic authorization when trying to generate a token

### ISSUE THREAD

**Issue by rawlingsj** [sdelements/lets-chat#517]
I've setup a user, jrawlings/password and want to curl /account/token/generate to generate a new token.

```
➜  ~  echo 'jrawlings:password' | base64
anJhd2xpbmdzOnBhc3N3b3JkCg==
```
Using the basic authorization I then use..
```
curl -X POST  -H "Content-type: application/json" -H "Authorization: Basic anJhd2xpbmdzOnBhc3N3b3JkCg==" http://myletschathost/account/token/generate
```
Which results in..
```
curl: (18) transfer closed with outstanding read data remaining
Unauthorized%
```
But also generates this error in the Lets Chat logs..

```
CastError: Cast to ObjectId failed for value "60)`" at path "_id"
    at ObjectId.cast (/usr/src/app/node_modules/mongoose/lib/schema/objectid.js:132:13)
    at ObjectId.castForQuery (/usr/src/app/node_modules/mongoose/lib/schema/objectid.js:182:17)
    at module.exports (/usr/src/app/node_modules/mongoose/lib/cast.js:201:32)
    at Query.cast (/usr/src/app/node_modules/mongoose/lib/query.js:2350:10)
    at Query.findOne (/usr/src/app/node_modules/mongoose/lib/query.js:1153:10)
    at Function.findOne (/usr/src/app/node_modules/mongoose/lib/model.js:1131:13)
    at Function.findById (/usr/src/app/node_modules/mongoose/lib/model.js:1068:15)
    at Function.UserSchema.statics.findByToken (/usr/src/app/app/models/user.js:182:10)
    at BasicStrategy.tokenAuth [as _verify] (/usr/src/app/app/auth/index.js:51:14)
    at BasicStrategy.authenticate (/usr/src/app/node_modules/passport-http/lib/passport-http/strategies/basic.js:97:10)
    at attempt (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at authenticate (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at /usr/src/app/app/middlewares/requireLogin.js:29:28
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express.oi/node_modules/express/lib/router/layer.js :95:5)
    at next (/usr/src/app/node_modules/express.oi/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/usr/src/app/node_modules/express.oi/node_modules/express/lib/router/route.js:112:3)
```

I know the [docs say that to use token as the user name](https://github.com/sdelements/lets-chat/wiki/API%3A-Authentication#basic-authentication) but if you have no token then its catch 22, also having a peak at the code it looked like this approach should support the `Authorization: Basic base64oftheusername:password` https://github.com/sdelements/lets-chat/blob/master/app/middlewares/requireLogin.js#L28

Should this work and if so is this a valid issue?

**Comment by jstrachan** [comment]
BTW this commit fixes it:
https://github.com/fabric8io/lets-chat/commit/74e5a66eb0f8d30ebd9d6bb8b9d599fe931ed5e8

**Comment by rawlingsj** [comment]
Thanks @jstrachan I'll close this as I understand how it works now.
