### ISSUE TITLE
Installation hangs when migrating 

### ISSUE THREAD

**Issue by vosgaust** [sdelements/lets-chat#520]
Hello, I'm trying to install let's chat on ubuntu 14.04.2 LTS, I have node v0.12.4, npm 2.1.18 and mongo 3.0.3. I follow these instructions: https://github.com/sdelements/lets-chat/wiki/Installation. I run `npm install` and no errors are given but some warnings, I attach the outout here: http://pastebin.com/waZ9Q5V4

Then configure the connection with mongodb in settings.yml `uri: mongodb://letschat:73190609@localhost/letschat`
Finally I `run npm start` and the output is the following:

```
bash-4.3$ npm start

> lets-chat@0.4.0 prestart /home/bitrock/lets-chat-0.4.0
> migroose
```

Then it hangs at that point and never ends. No error log is created. If I login the database I can see that something was created:

```
> show tables
messages
rooms
system.indexes
usermessages
users
```

Any idea? let me know if you need more information.

**Comment by mmeinert** [comment]
Are you sure the access to mongodb is protected ? try with `uri: mongodb://localhost/letschat` in your settings.yml

**Comment by vosgaust** [comment]
Yep, if I do that I get the following:
```
bash-4.3$ npm start

> lets-chat@0.4.0 prestart /home/bitrock/lets-chat-0.4.0
> migroose


events.js:85
      throw er; // Unhandled 'error' event
            ^
MongoError: not authorized for query on bitnami_letschat.migrootions
    at Function.MongoError.create (/home/bitrock/lets-chat-0.4.0/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/home/bitrock/lets-chat-0.4.0/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:170:34)
    at Callbacks.emit (/home/bitrock/lets-chat-0.4.0/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:94:3)
    at null.messageHandler (/home/bitrock/lets-chat-0.4.0/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:235:23)
    at Socket.<anonymous> (/home/bitrock/lets-chat-0.4.0/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:259:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

**Comment by mmeinert** [comment]
`MongoError: not authorized for query on bitnami_letschat.migrootions` bitnami ?(??) 
Are you sure you followed the installation instructions you referenced or you used an appliance/code from elsewhere ?

**Comment by vosgaust** [comment]
I'm using a stack that already comes with node, mongo and python but I'm installing let's chat using the instructions I mentioned.

**Comment by vosgaust** [comment]
I've just created a new database and user just to make sure with:
```
> use test
> db.createUser({user:"tester", pwd: "pass", roles: [{role:"dbOwner", db:"test"}]})
```
and running `npm start` still hangs and never ends.

**Comment by mmeinert** [comment]
If you can login with the credentials you mentioned on your first post :  `mongo localhost:27017/letschat -u letschat -p 73190609` This should work : `uri: mongodb://letschat:73190609@localhost:27017/letschat

If you can't, check your credentials.
