### ISSUE TITLE
crash on duplicate room slugs

### ISSUE THREAD

**Issue by 0vermind** [sdelements/lets-chat#525]
I'm running the docker image of 4.0
After 1 day of uptime it crashed. (maybe due to ram issue, maybe because of duplicate room slugs, I don't know exactly):

>{ [ValidationError: Room validation failed]
  message: 'Room validation failed',
  name: 'ValidationError',
  errors: 
   { slug: 
      { [ValidatorError: Expected slug to be unique]
        properties: [Object],
        message: 'Expected slug to be unique',
        name: 'ValidatorError',
        kind: 'user defined',
        path: 'slug',
        value: 'testroom' } } }
Killed
If i do node app restart:
>events.js:85
      throw er; // Unhandled 'error' event
            ^Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)

After the crash I cannot start the container anymore and there is nothing in docker logs so I don't know were else logs are saved.
Any suggestion?

**Comment by 0vermind** [comment]
I managed to solve the issue directly deleting the room associated with the not unique slug from the database. we need to add a check before saving duplicate slug.
