### ISSUE TITLE
Cannot login to XMPP server

### ISSUE THREAD

**Issue by oerdnj** [sdelements/lets-chat#545]
Any login ends with:

```
{ [ValidationError: User validation failed]
  stack: 'Error\n    at MongooseError.ValidationError (/var/www/lets-chat/node_modules/mongoose/lib/error/validation.js:22:16)\n    at model.Document.invalidate (/var/www/lets-chat/node_modules/mongoose/lib/document.js:1162:32)\n    at /var/www/lets-chat/node_modules/mongoose/lib/document.js:1037:16\n    at validate (/var/www/lets-chat/node_modules/mongoose/lib/schematype.js:651:7)\n    at /var/www/lets-chat/node_modules/mongoose/lib/schematype.js:676:11\n    at /var/www/lets-chat/node_modules/mongoose-unique-validator/index.js:43:9\n    at /var/www/lets-chat/node_modules/mongoose/lib/query.js:1174:16\n    at /var/www/lets-chat/node_modules/mongoose/node_modules/kareem/index.js:109:16\n    at process._tickCallback (node.js:419:13)',
  message: 'User validation failed',
  name: 'ValidationError',
  errors: 
   { username: 
      { [ValidatorError: Expected username to be unique]
        properties: [Object],
        stack: 'Error\n    at MongooseError.ValidatorError (/var/www/lets-chat/node_modules/mongoose/lib/error/validator.js:25:16)\n    at validate (/var/www/lets-chat/node_modules/mongoose/lib/schematype.js:650:13)\n    at /var/www/lets-chat/node_modules/mongoose/lib/schematype.js:676:11\n    at /var/www/lets-chat/node_modules/mongoose-unique-validator/index.js:43:9\n    at /var/www/lets-chat/node_modules/mongoose/lib/query.js:1174:16\n    at /var/www/lets-chat/node_modules/mongoose/node_modules/kareem/index.js:109:16\n    at process._tickCallback (node.js:419:13)',
        message: 'Expected username to be unique',
        name: 'ValidatorError',
        kind: 'user defined',
        path: 'username',
        value: 'ondrej' },
     email: 
      { [ValidatorError: Expected email to be unique]
        properties: [Object],
        stack: 'Error\n    at MongooseError.ValidatorError (/var/www/lets-chat/node_modules/mongoose/lib/error/validator.js:25:16)\n    at validate (/var/www/lets-chat/node_modules/mongoose/lib/schematype.js:650:13)\n    at /var/www/lets-chat/node_modules/mongoose/lib/schematype.js:676:11\n    at /var/www/lets-chat/node_modules/mongoose-unique-validator/index.js:43:9\n    at /var/www/lets-chat/node_modules/mongoose/lib/query.js:1174:16\n    at /var/www/lets-chat/node_modules/mongoose/node_modules/kareem/index.js:109:16\n    at process._tickCallback (node.js:419:13)',
        message: 'Expected email to be unique',
        name: 'ValidatorError',
        kind: 'user defined',
        path: 'email',
        value: 'o.....s....@n...cz' } } }
```

Perhaps it's related to https://github.com/sdelements/lets-chat-ldap/issues/16 ?

**Comment by bhat3** [comment]
@oerdnj Nice to see you hear on Node ;) But do you still have that issue?

I just got the same error messages while trying to self register a colleague on the local user database. Thought it might be due to an existing account, as i think the colleague already got an account, but i couldn't find him in the Mongo DB with
` # mongo
use letschat_prod
db.users.find({})`

**Comment by oerdnj** [comment]
@bhat3 Unfortunately I dropped playing with Let's Chat, so I have no idea.

**Comment by bhat3** [comment]
@oerdnj A that's sad we're still sticking to it in the company, especially cause it got an suberp XMPP support that you won't find in RocketChat, Mattermost & Co. But with local user database instead of LDAP it really got some limitations.

**Comment by bhat3** [comment]
Actually it was a fault on myside, that user was already registered, but i didn't found him in the database due to wrong use of the Mongo shell. Old SQL me didn't know you need to page in the user selection with Mongo:
```
# mongo
use DBNAME
db.users.find({})
it
```
@oerdnj Would recommend you close the ticket (i can't), as i couldn't verify it and there no other followers. See you again on PHP ;)

**Comment by bhat3** [comment]
@hhaidar BTW Thx for all your work on Let's Chat! Happy Eastern :)
