### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by tholu** [sdelements/lets-chat#548]
After a fresh git checkout on Debian, npm install fails with:

```
> node-stringprep@0.7.2 install /home/chat/lets-chat/node_modules/node-xmpp-core/node_modules/node-stringprep
> node-gyp rebuild


node.js:198
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object prototype may only be an Object or null
    at Function.create (native)
    at Object.inherits (util.js:465:27)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:63:6)
    at Module._compile (module.js:416:26)
    at Object..js (module.js:422:10)
    at Module.load (module.js:335:31)
    at Function._load (module.js:294:12)
    at Module.require (module.js:341:17)
    at require (module.js:352:17)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/readable-stream/readable.js:1:90)
/
> iconv@2.1.8 install /home/chat/lets-chat/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/node_modules/iconv
> node-gyp rebuild


node.js:198
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object prototype may only be an Object or null
    at Function.create (native)
    at Object.inherits (util.js:465:27)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:63:6)
    at Module._compile (module.js:416:26)
    at Object..js (module.js:422:10)
    at Module.load (module.js:335:31)
    at Function._load (module.js:294:12)
    at Module.require (module.js:341:17)
    at require (module.js:352:17)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/readable-stream/readable.js:1:90)
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! node-stringprep@0.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-stringprep@0.7.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-stringprep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-stringprep
npm ERR! There is likely additional logging output above.
```

**Comment by hhaidar** [comment]
You might need libicu:

```
sudo apt-get install libicu-dev
```

**Comment by tholu** [comment]
No, I already have that installed. Thanks for the suggestion! (should be listed under requirements, if needed)

**Comment by hhaidar** [comment]
That's usually the problem 90% of time :(

What happens when you install node-stringprep on its own: `npm install node-stringprep@latest`

**Comment by tholu** [comment]
Same problem, that's why I crossposted the issue to their repo.

**Comment by hhaidar** [comment]
@tholu ah cool, they will have a much better idea of what's going on. Sorry this is happening for you.

**Comment by tholu** [comment]
My mistake, problem was a stray old version of node (0.5.3) in ```/usr/local/bin/node```. Removed that and then it worked.

**Comment by hhaidar** [comment]
@tholu haha nice good to hear

**Comment by tholu** [comment]
I didn't notice at first because of
```
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
```
