### ISSUE TITLE
current docker with master totally broken

### ISSUE THREAD

**Issue by corn13read** [sdelements/lets-chat#559]
Digest: sha256:38f0a8a5c154a9cd947fb16329716cac35a5d7c9cadff0034904ea4eab47f793
Status: Downloaded newer image for sdelements/lets-chat:latest

> lets-chat@0.4.2 prestart /usr/src/app
> migroose

/usr/src/app/node_modules/mongodb/lib/server.js:228
        process.nextTick(function() { throw err; })
                                            ^
Error: getaddrinfo ENOTFOUND mongo
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)

npm ERR! Linux 2.6.32-504.16.2.el6.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! lets-chat@0.4.2 prestart: `migroose`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lets-chat@0.4.2 prestart script 'migroose'.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     migroose
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.
npm ERR! Linux 2.6.32-504.16.2.el6.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path npm-debug.log.7da2e9feb6af80ea1c45d89105a542fd
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, open 'npm-debug.log.7da2e9feb6af80ea1c45d89105a542fd'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, open 'npm-debug.log.7da2e9feb6af80ea1c45d89105a542fd']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: 'npm-debug.log.7da2e9feb6af80ea1c45d89105a542fd' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

**Comment by corn13read** [comment]
Built it myself and get the following:


root@3d84de5cb95f:/usr/src/app# npm start

> lets-chat@0.4.2 prestart /usr/src/app
> migroose


> lets-chat@0.4.2 start /usr/src/app
> node app.js


██╗     ███████╗████████╗███████╗     ██████╗██╗  ██╗ █████╗ ████████╗
██║     ██╔════╝╚══██╔══╝██╔════╝    ██╔════╝██║  ██║██╔══██╗╚══██╔══╝
██║     █████╗     ██║   ███████╗    ██║     ███████║███████║   ██║   
██║     ██╔══╝     ██║   ╚════██║    ██║     ██╔══██║██╔══██║   ██║   
███████╗███████╗   ██║   ███████║    ╚██████╗██║  ██║██║  ██║   ██║   
╚══════╝╚══════╝   ╚═╝   ╚══════╝     ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝

Release 0.4.2

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EAFNOSUPPORT
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1139:19)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)

npm ERR! Linux 2.6.32-504.16.2.el6.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! lets-chat@0.4.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lets-chat@0.4.2 start script 'node app.js'.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
root@3d84de5cb95f:/usr/src/app# cat /usr/src/app/npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart lets-chat@0.4.2
6 verbose unsafe-perm in lifecycle true
7 info start lets-chat@0.4.2
8 verbose unsafe-perm in lifecycle true
9 info lets-chat@0.4.2 Failed to exec start script
10 verbose stack Error: lets-chat@0.4.2 start: `node app.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid lets-chat@0.4.2
12 verbose cwd /usr/src/app
13 error Linux 2.6.32-504.16.2.el6.x86_64
14 error argv "node" "/usr/local/bin/npm" "start"
15 error node v0.12.7
16 error npm  v2.11.3
17 error code ELIFECYCLE
18 error lets-chat@0.4.2 start: `node app.js`
18 error Exit status 1
19 error Failed at the lets-chat@0.4.2 start script 'node app.js'.
19 error This is most likely a problem with the lets-chat package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node app.js
19 error You can get their info via:
19 error     npm owner ls lets-chat
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by hhaidar** [comment]
What platform are you on? Also have you tried enabling ipv6?

**Comment by thisgeekza** [comment]
The problem is that the database alias is no longer 'db' it is now 'mongo'.

**Comment by greggigon** [comment]
Just now tried the latest and it is breaking with the same errors. Any workaround?

**Comment by greggigon** [comment]
Hm ... 
Starting both Mongo and Let's-Chat manually (not with docker-compose) works. Seems like Mongo doesn't start fast enough and Let's-Chat flips over as cannot establish a connection.

**Comment by sibartlett** [comment]
@greggigon does your docker-compose file use "mongo" as the database alias?

**Comment by greggigon** [comment]
Yes, it does. Should I use "db" as alias ?

**Comment by sibartlett** [comment]
@greggigon "mongo is correct. It's weird that docker-compose doesn't work! This [docker-compose.yml](https://github.com/sdelements/lets-chat/blob/master/docker/docker-compose.yml) worked for me when I last tested it, I will retest it.

**Comment by greggigon** [comment]
Docker Compose has no concept of service being up. So when LC has a link to Mongo, as soon as Mongo container starts, LC container is being lunched. 
It is possible on slower systems that Mongo is still initialising when LC tries to make it's initial connection during "migroose" and fails. 
Would be good to wrap LC entry point into small script which tries MongoDB connection for few seconds and fails after few attempts.

**Comment by hhaidar** [comment]
@greggigon that's a little annoying :/

Maybe something like this could work: https://github.com/docker/docker/issues/7445#issuecomment-101523662
