### ISSUE TITLE
installing node

### ISSUE THREAD

**Issue by putty123** [sdelements/lets-chat#592]
clarion@clarion-Vostro-1014 ~ $ node app.js

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/clarion/app.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
i got this error while running node app.js. and i cant access localhost:3000- page is not available

**Comment by putty123** [comment]
please help me with this issue.

**Comment by mtrycz** [comment]
It's obviously not an inssue with the application, but a configuration issue.
Most likely you're not in the right directory: the file "/home/clarion/app.js" does not exist. Most likely you've cloned the repository into another directory ("lets-chat" would be likely).  Try to run the app from there.

**Comment by hhaidar** [comment]
yea you need to do `cd lets-chat`

also please make sure you've installed everything as [mentioned in the docs](https://github.com/sdelements/lets-chat/wiki/Installation)
