### ISSUE TITLE
prestart script fails with: "sh: 1: migroose: Permission denied"

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [sdelements/lets-chat#597]
I know there is already an issue here on this, but it is closed and there is no clue on how to solve this. Also in the google group there is no hint.

Also my newer npm version delivers a little more output about the stack than what was in the previous issues.

The issue is the following:

    root@servername:/home/lets-chat# npm start

    > lets-chat@0.4.2 prestart /home/lets-chat
    > migroose

    sh: 1: migroose: Permission denied

    npm ERR! Linux 3.2.0-4-amd64
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
    npm ERR! node v0.12.7
    npm ERR! npm  v2.11.3
    npm ERR! code ELIFECYCLE
    npm ERR! lets-chat@0.4.2 prestart: `migroose`
    npm ERR! Exit status 126
    npm ERR!
    npm ERR! Failed at the lets-chat@0.4.2 prestart script 'migroose'.
    npm ERR! This is most likely a problem with the lets-chat package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     migroose
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls lets-chat
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/lets-chat/npm-debug.log

The output of npm-debug.log is:

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
    2 info using npm@2.11.3
    3 info using node@v0.12.7
    4 verbose node symlink /usr/bin/node
    5 verbose run-script [ 'prestart', 'start', 'poststart' ]
    6 info prestart lets-chat@0.4.2
    7 verbose unsafe-perm in lifecycle true
    8 info lets-chat@0.4.2 Failed to exec prestart script
    9 verbose stack Error: lets-chat@0.4.2 prestart: `migroose`
    9 verbose stack Exit status 126
    9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
    9 verbose stack     at EventEmitter.emit (events.js:110:17)
    9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
    9 verbose stack     at ChildProcess.emit (events.js:110:17)
    9 verbose stack     at maybeClose (child_process.js:1015:16)
    9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
    10 verbose pkgid lets-chat@0.4.2
    11 verbose cwd /home/lets-chat
    12 error Linux 3.2.0-4-amd64
    13 error argv "/usr/bin/node" "/usr/bin/npm" "start"
    14 error node v0.12.7
    15 error npm  v2.11.3
    16 error code ELIFECYCLE
    17 error lets-chat@0.4.2 prestart: `migroose`
    17 error Exit status 126
    18 error Failed at the lets-chat@0.4.2 prestart script 'migroose'.
    18 error This is most likely a problem with the lets-chat package,
    18 error not with npm itself.
    18 error Tell the author that this fails on your system:
    18 error     migroose
    18 error You can get their info via:
    18 error     npm owner ls lets-chat
    18 error There is likely additional logging output above.
    19 verbose exit [ 1, true ]

Does anyone have a clue?
mongodb is up and running fine. 
the mongo log contains:

    [initandlisten] waiting for connections on port 27017

mongodb is version 3.0.6.
I am running this on debian wheezy.

**Comment by hhaidar** [comment]
can you connect to mongo via the command line client?

**Comment by 1337sup3rh4x0r** [comment]
Thanks for looking into this! Do you mean the mongodb shell? Yes, that works. I can type

    mongo

In the shell and then for example list the dbs with 

    show dbs

**Comment by mtrycz** [comment]
Have you tried this?
http://sourcode.net/sh-1-node-permission-denied/

Anyway, I think that generally you'll get problems with running node as root. Did you try switching users?

**Comment by 1337sup3rh4x0r** [comment]
Thanks for the input!
However both didn't work. Neither the command from your link, nor creating a dedicated user for letschat, making him the folder owner and running `npm start` through him.

The error output stays exactly the same.

**Comment by sploadie** [comment]
I believe my solution to this error was

~~~ bash
sudo -u lets-chat npm start
~~~

where my dedicated Let's Chat user was named `lets-chat`.

**Comment by kaushik94** [comment]
@sploadie won't be able to run on a docker instance with sudo.
