### ISSUE TITLE
Cannot read property 'cookie' of undefined

### ISSUE THREAD

**Issue by hzruandd** [sdelements/lets-chat#604]
trace back:
> lets-chat@0.4.2 start /Users/jake/chuangye/chat/lets-chat
> node app.js

██╗     ███████╗████████╗███████╗     ██████╗██╗  ██╗ █████╗ ████████╗
██║     ██╔════╝╚══██╔══╝██╔════╝    ██╔════╝██║  ██║██╔══██╗╚══██╔══╝
██║     █████╗     ██║   ███████╗    ██║     ███████║███████║   ██║   
██║     ██╔══╝     ██║   ╚════██║    ██║     ██╔══██║██╔══██║   ██║   
███████╗███████╗   ██║   ███████║    ╚██████╗██║  ██║██║  ██║   ██║   
╚══════╝╚══════╝   ╚═╝   ╚══════╝     ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝

Release 0.4.2

/Users/jake/chuangye/chat/lets-chat/node_modules/connect-mongo/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
TypeError: Cannot read property 'cookie' of undefined
    at /Users/jake/chuangye/chat/lets-chat/node_modules/passport.socketio/lib/index.js:20:22
    at Array.<anonymous> (/Users/jake/chuangye/chat/lets-chat/app/auth/index.js:96:13)
    at run (/Users/jake/chuangye/chat/lets-chat/node_modules/express.oi/node_modules/socket.io/lib/namespace.js:114:11)
    at /Users/jake/chuangye/chat/lets-chat/node_modules/express.oi/node_modules/socket.io/lib/namespace.js:122:7
    at /Users/jake/chuangye/chat/lets-chat/node_modules/express.oi/lib/session.js:61:7
    at /Users/jake/chuangye/chat/lets-chat/node_modules/express.oi/lib/session.js:48:9
    at /Users/jake/chuangye/chat/lets-chat/node_modules/express.oi/node_modules/express-session/session/store.js:63:5
    at /Users/jake/chuangye/chat/lets-chat/node_modules/connect-mongo/lib/connect-mongo.js:305:11
    at handleCallback (/Users/jake/chuangye/chat/lets-chat/node_modules/connect-mongo/node_modules/mongodb/lib/utils.js:95:12)
    at /Users/jake/chuangye/chat/lets-chat/node_modules/connect-mongo/node_modules/mongodb/lib/collection.js:1122:5
    at handleCallback (/Users/jake/chuangye/chat/lets-chat/node_modules/connect-mongo/node_modules/mongodb/lib/utils.js:95:12)
    at /Users/jake/chuangye/chat/lets-chat/node_modules/connect-mongo/node_modules/mongodb/lib/cursor.js:597:5
    at handleCallback (/Users/jake/chuangye/chat/lets-chat/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:244:5)
    at nextFunction (/Users/jake/chuangye/chat/lets-chat/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:739:5)
    at /Users/jake/chuangye/chat/lets-chat/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:664:7
    at queryCallback (/Users/jake/chuangye/chat/lets-chat/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:321:5)

**Comment by sibartlett** [comment]
I think this is now fixed. Some of the dependencies we rely on were updated with breaking changes. Pulling the latest code, and nam installing should fix this.

**Comment by hzruandd** [comment]
Yes, thanks. i had got it.
