### ISSUE TITLE
Install on Debian 8.1

### ISSUE THREAD

**Issue by duchydev** [sdelements/lets-chat#620]
Hello,

i`ve tried to install Lets Chat on my Debian 8.1 Server. 
I have installed:

mongodb version: 2.4.10
nodejs version: v0.10.29
npm version: 1.4.21
make version: 4.0
gcc version: 4.9.2
python version: 2.7.9

When i try "npm install" then i got these Errors, could you help me? 

lets-chat$ npm install
npm WARN deprecated MD5@1.2.2: deprecated, use lowercase 'md5@2.x' from now on
npm WARN engine mongoose-validate@0.0.5: wanted: {"node":"0.8.x"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN optional dep failed, continuing fsevents@0.3.8

> utf-8-validate@1.1.0 install /usr/local/haba/lets-chat/node_modules/node-xmpp-server/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/usr/local/haba/lets-chat/node_modules/node-xmpp-server/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory '/usr/local/haba/lets-chat/node_modules/node-xmpp-server/node_modules/ws/node_modules/utf-8-validate/build'

> bufferutil@1.1.0 install /usr/local/haba/lets-chat/node_modules/node-xmpp-server/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/usr/local/haba/lets-chat/node_modules/node-xmpp-server/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory '/usr/local/haba/lets-chat/node_modules/node-xmpp-server/node_modules/ws/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /usr/local/haba/lets-chat/node_modules/express.oi/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/usr/local/haba/lets-chat/node_modules/express.oi/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:0:
../node_modules/nan/nan.h:316:47: error: âREPLACE_INVALID_UTF8â is not a member of âv8::Stringâ
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
validation.target.mk:86: recipe for target 'Release/obj.target/validation/src/validation.o' failed
make: *** [Release/obj.target/validation/src/validation.o] Error 1
make: Leaving directory '/usr/local/haba/lets-chat/node_modules/express.oi/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/haba/lets-chat/node_modules/express.oi/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN optional dep failed, continuing utf-8-validate@1.2.1

> bufferutil@1.2.1 install /usr/local/haba/lets-chat/node_modules/express.oi/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/usr/local/haba/lets-chat/node_modules/express.oi/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:0:
../node_modules/nan/nan.h:316:47: error: âREPLACE_INVALID_UTF8â is not a member of âv8::Stringâ
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
bufferutil.target.mk:86: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
make: Leaving directory '/usr/local/haba/lets-chat/node_modules/express.oi/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/haba/lets-chat/node_modules/express.oi/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN optional dep failed, continuing bufferutil@1.2.1
npm WARN engine hawk@3.1.0: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.29","npm":"1.4.21"})

> kerberos@0.0.15 install /usr/local/haba/lets-chat/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/usr/local/haba/lets-chat/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: Datei oder Verzeichnis nicht gefunden
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
kerberos.target.mk:88: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/usr/local/haba/lets-chat/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/haba/lets-chat/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN engine boom@2.9.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})

> bson-ext@0.1.13 install /usr/local/haba/lets-chat/node_modules/mongoose/node_modules/bson/node_modules/bson-ext
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/usr/local/haba/lets-chat/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
bson.target.mk:82: recipe for target 'Release/obj.target/bson/ext/bson.o' failed
make: Leaving directory '/usr/local/haba/lets-chat/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build'

> kerberos@0.0.15 install /usr/local/haba/lets-chat/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/usr/local/haba/lets-chat/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: Datei oder Verzeichnis nicht gefunden
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
kerberos.target.mk:88: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/usr/local/haba/lets-chat/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/haba/lets-chat/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN engine hawk@3.1.0: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@2.9.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm ERR! fetch failed https://github.com/dodo/reconnect-core/tarball/merged
npm ERR! fetch failed https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz

**Comment by hhaidar** [comment]
@duchydev http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu

**Comment by duchydev** [comment]
@hhaidar thanks for your answer, but node and nodejs is always on the /usr/bin/node and /usr/bin/nodejs path.... and nodejs-legacy is installed, too. Have you any other ideas?

**Comment by bascht** [comment]
@duchydev I'm not a npm pro, but those "fetch failed" look a bit like network connectivity issues to me.
