### ISSUE TITLE
Docker image wont start

### ISSUE THREAD

**Issue by cjbarnes18** [sdelements/lets-chat#621]
When using the docker-compose.yml file, on up I see.

```
$ docker-compose up
Recreating docker_mongo_1...
Recreating docker_app_1...
Attaching to docker_mongo_1, docker_app_1
mongo_1 | 2015-10-12T19:54:45.724+0000 I JOURNAL  [initandlisten] journal dir=/data/db/journal
mongo_1 | 2015-10-12T19:54:45.724+0000 I JOURNAL  [initandlisten] recover : no journal files present, no recovery needed
app_1   | 
app_1   | > lets-chat@0.4.3 prestart /usr/src/app
app_1   | > migroose
app_1   | 
mongo_1 | 2015-10-12T19:55:02.885+0000 I JOURNAL  [initandlisten] preallocateIsFaster=true 74
app_1   | 
app_1   | /usr/src/app/node_modules/mongodb/lib/server.js:228
app_1   |         process.nextTick(function() { throw err; })
app_1   |                                             ^
app_1   | Error: connect ECONNREFUSED
app_1   |     at exports._errnoException (util.js:746:11)
app_1   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
app_1   | 
app_1   | npm ERR! Linux 3.16.0-4-amd64
app_1   | npm ERR! argv "node" "/usr/local/bin/npm" "start"
app_1   | npm ERR! node v0.12.7
app_1   | npm ERR! npm  v2.14.1
app_1   | npm ERR! code ELIFECYCLE
app_1   | npm ERR! lets-chat@0.4.3 prestart: `migroose`
app_1   | npm ERR! Exit status 1
app_1   | npm ERR! 
app_1   | npm ERR! Failed at the lets-chat@0.4.3 prestart script 'migroose'.
app_1   | npm ERR! This is most likely a problem with the lets-chat package,
app_1   | npm ERR! not with npm itself.
app_1   | npm ERR! Tell the author that this fails on your system:
app_1   | npm ERR!     migroose
app_1   | npm ERR! You can get their info via:
app_1   | npm ERR!     npm owner ls lets-chat
app_1   | npm ERR! There is likely additional logging output above.
app_1   | npm ERR! Linux 3.16.0-4-amd64
app_1   | npm ERR! argv "node" "/usr/local/bin/npm" "start"
app_1   | npm ERR! node v0.12.7
app_1   | npm ERR! npm  v2.14.1
app_1   | npm ERR! path npm-debug.log.7da2e9feb6af80ea1c45d89105a542fd
app_1   | npm ERR! code EACCES
app_1   | npm ERR! errno -13
app_1   | 
app_1   | npm ERR! Error: EACCES, open 'npm-debug.log.7da2e9feb6af80ea1c45d89105a542fd'
app_1   | npm ERR!     at Error (native)
app_1   | npm ERR!  { [Error: EACCES, open 'npm-debug.log.7da2e9feb6af80ea1c45d89105a542fd']
app_1   | npm ERR!   errno: -13,
app_1   | npm ERR!   code: 'EACCES',
app_1   | npm ERR!   path: 'npm-debug.log.7da2e9feb6af80ea1c45d89105a542fd' }
app_1   | npm ERR! 
app_1   | npm ERR! Please try running this command again as root/Administrator.
app_1   | 
app_1   | npm ERR! Please include the following file with any support request:
app_1   | npm ERR!     /usr/src/app/npm-debug.log
docker_app_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Stopping docker_mongo_1...
```

**Comment by vwbusguy** [comment]
This means it's not able to connect to your Mongo server.

**Comment by liquidstate** [comment]
I had the same problem, it looks to be a race condition whereby `docker-compose` doesn't wait for a dependant container to fully start before starting the parent.  So, specifically, `docker-compose` is starting the `docker_mongo_1` container but it hasn't started listening for connections before the `docker_app_1` containers starts and tries to connect to it.  `docker_app_1` tries once, and if that fails (`connect ECONNREFUSED`), it bombs out.

The problem is detailed in more depth, along with potential solutions [at the docker website](https://docs.docker.com/compose/startup-order/)

I think the best solution would be for the `sdelements/lets-chat` image to be modified to include an ability to either wait for MongoDB to be listening on the target port or retry the connection a few times, rather than bailing out after the first attempt.  Perhaps something as simple as [wait-for-it.sh](https://github.com/vishnubob/wait-for-it) might do the trick.

I fuddled around it in the short term by removing my lets-chat container before starting the rest (`docker-compose rm app; docker-compose up`) - and usually the delay in building the container was long enough for MongoDB to get started.
