### ISSUE TITLE
Docker container won't start

### ISSUE THREAD

**Issue by darthzen** [sdelements/lets-chat#690]
Trying to run the docker container (either pulling from GitHub or building from scratch with the Dockerfile) results in the following error:

/usr/src/app/node_modules/connect-mongo/src/index.js:3
const Promise = require('bluebird');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/src/app/node_modules/connect-mongo/index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/src/app/app.js:24:20)
    at Module._compile (module.js:460:26)

**Comment by hhaidar** [comment]
Sorry about that, can you try pulling again?

**Comment by hhaidar** [comment]
git p
