### ISSUE TITLE
Docker image does not work

### ISSUE THREAD

**Issue by vijayrajah** [sdelements/lets-chat#695]
I deployed a docker image from docer hub.

I was followed the steps as per the wiki. I'm getting "EACCESS" error like...

```
.
.
.

Error: EACCES, permission denied '/usr/src/app/builtAssets'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:747:18)
    at sync (/usr/src/app/node_modules/mkdirp/index.js:71:13)
    at write (/usr/src/app/node_modules/connect-assets/node_modules/mincer/lib/mincer/manifest.js:148:5)
    at /usr/src/app/node_modules/connect-assets/node_modules/mincer/lib/mincer/manifest.js:254:5
    at Array.forEach (native)
    at Manifest.compile (/usr/src/app/node_modules/connect-assets/node_modules/mincer/lib/mincer/manifest.js:219:9)
    at Assets.compile (/usr/src/app/node_modules/connect-assets/lib/assets.js:50:39)
    at module.exports (/usr/src/app/node_modules/connect-assets/index.js:24:10)
    at Object.<anonymous> (/usr/src/app/app.js:105:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
.
.


```

How do i fix this?

**Comment by hhaidar** [comment]
@vijayrajah can you try again?

**Comment by hhaidar** [comment]
Works for us, please reopen if you're still encountering this issue.
