### ISSUE TITLE
npm install - cannot find module cyclic.js

### ISSUE THREAD

**Issue by Cibiksebak** [sdelements/lets-chat#725]
```
root@myserver:~/lets-chat# npm install
    npm WARN engine mongoose-validate@0.0.5: wanted: {"node":"0.8.x"} (current: {"node":"4.6.2","npm":"2.15.11"})
    npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
    npm WARN deprecated wrench@1.4.4: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
    npm WARN engine csswring@5.0.0: wanted: {"node":">=5.0.0"} (current: {"node":"4.6.2","npm":"2.15.11"})
    npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
    npm WARN deprecated graceful-fs@1.1.14: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
    npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
    npm WARN optional dep failed, continuing fsevents@1.0.15

> typechecker@2.0.8 preinstall /root/lets-chat/node_modules/i18n/node_modules/messageformat/node_modules/watchr/node_modules/extendr/node_modules/typechecker
> node ./cyclic.js

module.js:327
    throw err;
    ^

Error: Cannot find module '/root/lets-chat/node_modules/i18n/node_modules/messageformat/node_modules/watchr/node_modules/extendr/node_modules/typechecker/cyclic.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3

> typechecker@2.0.8 preinstall /root/lets-chat/node_modules/i18n/node_modules/messageformat/node_modules/watchr/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js

module.js:327
    throw err;
    ^

Error: Cannot find module '/root/lets-chat/node_modules/i18n/node_modules/messageformat/node_modules/watchr/node_modules/extract-opts/node_modules/typechecker/cyclic.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
npm WARN deprecated mongodb@2.2.11: please upgrade to 2.2.12 or higher
npm WARN deprecated tough-cookie@0.12.1: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine punycode@2.0.1: wanted: {"node":">=6"} (current: {"node":"4.6.2","npm":"2.15.11"})
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.6.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! typechecker@2.0.8 preinstall: `node ./cyclic.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the typechecker@2.0.8 preinstall script 'node ./cyclic.js'.
npm ERR! This is most likely a problem with the typechecker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./cyclic.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs typechecker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls typechecker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/lets-chat/npm-debug.log
```

Any suggestions please? What's wrong with the installation and how should I fix it? Thanks.

**Comment by vineethvijay-MyT** [comment]
Any luck with this?
